// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKsaUmbZlJkaf8GroyP7Nu02M3z6X8cCs',
    appId: '1:226167656381:web:d84b1f81ed1f57a92eccd4',
    messagingSenderId: '226167656381',
    projectId: 'popticle-f034d',
    authDomain: 'popticle-f034d.firebaseapp.com',
    storageBucket: 'popticle-f034d.appspot.com',
    measurementId: 'G-CRCEE5DCYZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu5ni4q48edTiPG7o2NmFIE47AFE2wCps',
    appId: '1:226167656381:android:44a8a105b1a9857b2eccd4',
    messagingSenderId: '226167656381',
    projectId: 'popticle-f034d',
    storageBucket: 'popticle-f034d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG5aFeHoBnkcdf7ei4kD_CIf0blbmxDvE',
    appId: '1:226167656381:ios:c2a1fef7c750cd3a2eccd4',
    messagingSenderId: '226167656381',
    projectId: 'popticle-f034d',
    storageBucket: 'popticle-f034d.appspot.com',
    iosBundleId: 'com.example.popticle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDG5aFeHoBnkcdf7ei4kD_CIf0blbmxDvE',
    appId: '1:226167656381:ios:c414106af7dd26bc2eccd4',
    messagingSenderId: '226167656381',
    projectId: 'popticle-f034d',
    storageBucket: 'popticle-f034d.appspot.com',
    iosBundleId: 'com.example.popticle.RunnerTests',
  );
}
